def draw_lake():
    #print("lake not found")
    print("                                             *                  ")
    print("                                            ***                 ")
    print("                                           *****                ")
    print("                             ~~~~~        ***|***               ")
    print("     *         ~~~~~       /       \        *|*                 ")
    print("    ***      /        \~~~~~         \___    |                  ")
    print("   *****    /                             ~~~~~                 ")
    print("  ***|***  {                                   \                ")
    print("    *|*  ~~           //                  ^     \               ")
    print("     |  /                               <( )>    ~~~~~~~~       ")
    print("    ~~~          //                 //    x              \      ")
    print("  {                                                       }     ")
    print("  {                ^                     ( (o) )          }     ")
    print("   \             /{ }\  //                                }     ")
    print("     \    //       x                    //               /      ")
    print("       \        ~~~~~~                 //               /       ")
    print("         ~~~~ /        \                              ~~        ")
    print("                         \                           /          ")
    print("                           ~~~~~~~~~~~~~~~~~~~~~~~~~            ")    
    
    return
